create extension if not exists btree_gist with schema extensions;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'pending'
    check (role in ('pending', 'scheduling_admin', 'global_admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.courts (
  id text primary key check (id in ('A', 'B')),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.players (
  id bigint generated by default as identity primary key,
  full_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index players_full_name_unique
  on public.players (lower(trim(full_name)));

create table public.player_private (
  player_id bigint primary key references public.players(id) on delete cascade,
  residence text,
  booking_reputation text not null default 'Clear',
  phone text,
  in_whatsapp boolean,
  updated_at timestamptz not null default now()
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  court_id text not null references public.courts(id),
  title text not null,
  booking_type text not null
    check (booking_type in ('mabar_warga', 'private', 'non_warga', 'incidental', 'basket')),
  priority smallint check (priority between 1 and 3),
  resident_ratio text not null default 'not_applicable'
    check (resident_ratio in ('gte_50', 'lt_50', 'not_applicable')),
  start_at timestamptz not null,
  end_at timestamptz not null,
  status text not null default 'confirmed'
    check (status in ('confirmed', 'cancelled', 'no_show')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_valid_duration check (end_at > start_at),
  constraint bookings_operating_hours check (
    (start_at at time zone 'Asia/Jakarta')::time >= time '05:00'
    and (end_at at time zone 'Asia/Jakarta')::time <= time '22:00'
    and (start_at at time zone 'Asia/Jakarta')::date = (end_at at time zone 'Asia/Jakarta')::date
  ),
  constraint bookings_no_overlap exclude using gist (
    court_id with =,
    tstzrange(start_at, end_at, '[)') with &&
  ) where (status = 'confirmed')
);

create index bookings_start_at_idx on public.bookings (start_at);
create index bookings_court_start_idx on public.bookings (court_id, start_at);

create table public.booking_players (
  booking_id uuid not null references public.bookings(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  is_resident boolean not null default true,
  primary key (booking_id, player_id)
);

create table public.audit_events (
  id bigint generated always as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.touch_updated_at();
create trigger players_touch_updated_at before update on public.players
for each row execute function public.touch_updated_at();
create trigger player_private_touch_updated_at before update on public.player_private
for each row execute function public.touch_updated_at();
create trigger bookings_touch_updated_at before update on public.bookings
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role
  from public.profiles
  where id = (select auth.uid()) and is_active = true
  limit 1;
$$;

create or replace function public.can_schedule()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_user_role() in ('scheduling_admin', 'global_admin'), false);
$$;

create or replace function public.is_global_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_user_role() = 'global_admin', false);
$$;

create or replace function public.set_user_access(
  target_user_id uuid,
  new_role text,
  new_is_active boolean default true
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.profiles;
begin
  if not public.is_global_admin() then
    raise exception 'Only global administrators can change access';
  end if;

  if new_role not in ('pending', 'scheduling_admin', 'global_admin') then
    raise exception 'Invalid role';
  end if;

  update public.profiles
  set role = new_role, is_active = new_is_active, updated_at = now()
  where id = target_user_id
  returning * into result;

  if result.id is null then
    raise exception 'User profile not found';
  end if;

  insert into public.audit_events (actor_id, entity_type, entity_id, action, detail)
  values ((select auth.uid()), 'profile', target_user_id::text, 'set_user_access', jsonb_build_object('role', new_role, 'is_active', new_is_active));

  return result;
end;
$$;

create or replace function public.audit_booking_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  changed_id text;
begin
  if tg_op = 'DELETE' then
    changed_id := old.id::text;
  else
    changed_id := new.id::text;
  end if;
  insert into public.audit_events (actor_id, entity_type, entity_id, action, detail)
  values (
    (select auth.uid()),
    'booking',
    changed_id,
    lower(tg_op),
    case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger bookings_audit
after insert or update or delete on public.bookings
for each row execute function public.audit_booking_change();

alter table public.profiles enable row level security;
alter table public.courts enable row level security;
alter table public.players enable row level security;
alter table public.player_private enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_players enable row level security;
alter table public.audit_events enable row level security;

create policy profiles_read_own_or_global on public.profiles
for select to authenticated
using (id = (select auth.uid()) or public.is_global_admin());

create policy profiles_update_own_name on public.profiles
for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy courts_public_read on public.courts
for select to anon, authenticated using (true);
create policy courts_global_write on public.courts
for all to authenticated using (public.is_global_admin()) with check (public.is_global_admin());

create policy players_public_read on public.players
for select to anon, authenticated using (is_active = true);
create policy players_admin_read_all on public.players
for select to authenticated using (public.can_schedule());
create policy players_global_write on public.players
for all to authenticated using (public.is_global_admin()) with check (public.is_global_admin());

create policy player_private_admin_read on public.player_private
for select to authenticated using (public.can_schedule());
create policy player_private_global_write on public.player_private
for all to authenticated using (public.is_global_admin()) with check (public.is_global_admin());

create policy bookings_public_read on public.bookings
for select to anon, authenticated
using (status = 'confirmed');
create policy bookings_admin_read_all on public.bookings
for select to authenticated using (public.can_schedule());
create policy bookings_admin_insert on public.bookings
for insert to authenticated with check (public.can_schedule());
create policy bookings_admin_update on public.bookings
for update to authenticated using (public.can_schedule()) with check (public.can_schedule());
create policy bookings_admin_delete on public.bookings
for delete to authenticated using (public.can_schedule());

create policy booking_players_admin_read on public.booking_players
for select to authenticated using (public.can_schedule());
create policy booking_players_admin_write on public.booking_players
for all to authenticated using (public.can_schedule()) with check (public.can_schedule());

create policy audit_global_read on public.audit_events
for select to authenticated using (public.is_global_admin());

revoke all on public.profiles, public.courts, public.players, public.player_private,
  public.bookings, public.booking_players, public.audit_events from anon, authenticated;

grant select on public.courts, public.players, public.bookings to anon, authenticated;
grant select on public.profiles, public.player_private, public.booking_players, public.audit_events to authenticated;
grant insert, update, delete on public.bookings, public.booking_players to authenticated;
grant insert, update, delete on public.courts, public.players, public.player_private to authenticated;
grant update (full_name) on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.current_user_role() from public, anon;
revoke all on function public.can_schedule() from public, anon;
revoke all on function public.is_global_admin() from public, anon;
revoke all on function public.set_user_access(uuid, text, boolean) from public, anon;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.can_schedule() to authenticated;
grant execute on function public.is_global_admin() to authenticated;
grant execute on function public.set_user_access(uuid, text, boolean) to authenticated;

insert into public.courts (id, name) values
  ('A', 'Lapangan A'),
  ('B', 'Lapangan B');
